package com.example.SalesTransactionService.SalesTransaction.mappers.DeliveryOrder;



import com.example.SalesTransactionService.SalesTransaction.dtos.RequestDto.DeliveryOrder.DeliveryOrderRequestDto;
import com.example.SalesTransactionService.SalesTransaction.dtos.ResponseDto.DeliveryOrder.DeliveryOrderResponseDto;
import com.example.SalesTransactionService.SalesTransaction.models.DeliveryOrder.DeliveryOrderLineItem;
import com.example.SalesTransactionService.SalesTransaction.dtos.RequestDto.DeliveryOrder.LineItemRequestDto;
import com.example.SalesTransactionService.SalesTransaction.dtos.ResponseDto.DeliveryOrder.LineItemResponseDto;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface DeliveryOrderLineItemMapper {

    // Map Request DTO to Entity
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "deliveryOrder", ignore = true) // Relationship handled by parent mapper/service
    @Mapping(target = "totalPrice", ignore = true) // Calculated in entity/service
    DeliveryOrderLineItem toEntity(DeliveryOrderRequestDto dto);

    // Map Entity to Response DTO
    DeliveryOrderResponseDto toEntity(DeliveryOrderLineItem entity);
}