package com.example.SalesTransactionService.SalesTransaction.mappers;


import com.example.SalesTransactionService.SalesTransaction.dtos.RequestDto.ProformaInvoiceRequestDto;
import com.example.SalesTransactionService.SalesTransaction.dtos.ResponseDto.ProformaInvoiceResponseDto;
import com.example.SalesTransactionService.SalesTransaction.models.Voucher.ItemPriceDetail;
import com.example.SalesTransactionService.SalesTransaction.dtos.RequestDto.ItemPriceDetailRequestDto;
import com.example.SalesTransactionService.SalesTransaction.dtos.ResponseDto.ItemPriceDetailResponseDto;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.math.BigDecimal;

@Mapper(componentModel = "spring")
public interface ItemPriceDetailMapper{

    // Map Request DTO to Entity
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "proformaInvoice", ignore = true) // Relationship handled by parent mapper/service
    @Mapping(target = "itemTaxAmount", ignore = true) // Calculated in entity/service
    @Mapping(target = "totalPrice", ignore = true) // Calculated in entity/service
    ItemPriceDetail toEntity(ProformaInvoiceRequestDto dto);


    ProformaInvoiceResponseDto.ItemPriceDetailResponseDto toDto(ItemPriceDetail);

  //   For updating existing line item entity
     @Mapping(target = "id", ignore = true)
     @Mapping(target = "proformaInvoice", ignore = true)
     @Mapping(target = "itemTaxAmount", ignore = true)
     @Mapping(target = "totalPrice", ignore = true)
     void updateEntityFromDto(ProformaInvoiceRequestDto.LineItemRequest dto, @MappingTarget ProformaInvoiceLineItem entity);
}

// Map Entity to Response DTO
//    ProformaInvoiceResponseDto.ItemPriceDetailResponseDto toDto(ItemPriceDetail entity);
//
//    // For updating an existing entity
//    @Mapping(target = "id", ignore = true)
//    @Mapping(target = "proformaInvoice", ignore = true)
//    @Mapping(target = "itemTaxAmount", ignore = true)
//    @Mapping(target = "totalPrice", ignore = true)
//    void updateEntityFromDto(ProformaInvoiceRequestDto.ItemPriceDetailRequestDto dto, @MappingTarget ItemPriceDetail entity);