package com.example.SalesTransactionService.SalesTransaction.mappers;

import com.example.SalesTransactionService.SalesTransaction.dtos.RequestDto.ItemDetailRequestDto;
import com.example.SalesTransactionService.SalesTransaction.models.AgreementRegistration.ItemDetail;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.factory.Mappers;

// Ensure this mapper knows about ServiceCenterMapper and TaxCenterRegionMapper
@Mapper(componentModel = "spring", uses = {ServiceCenterMapper.class, TaxCenterRegionMapper.class})
public interface ItemDetailMapper {

    ItemDetailMapper INSTANCE = Mappers.getMapper(ItemDetailMapper.class);

    @Mapping(target = "id", ignore = true) // ID generated by DB
    @Mapping(target = "contractAgreement", ignore = true) // Relationship set in parent mapper/service
    @Mapping(target = "serviceCenter", ignore = true) // Set by service based on serviceCenterId
    @Mapping(target = "taxCenterRegion", ignore = true) // Set by service based on taxCenterRegionId
    ItemDetail toEntity(ItemDetailRequestDto dto);

    @Mapping(source = "serviceCenter.id", target = "serviceCenterId")
    @Mapping(source = "serviceCenter.name", target = "serviceCenterName")
    @Mapping(source = "taxCenterRegion.id", target = "taxCenterRegionId")
    @Mapping(source = "taxCenterRegion.name", target = "taxCenterRegionName")
    ItemDetailRequestDto toResponseDto(ItemDetail entity);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "contractAgreement", ignore = true)
    @Mapping(target = "serviceCenter", ignore = true)
    @Mapping(target = "taxCenterRegion", ignore = true)
    void updateEntityFromDto(ItemDetailRequestDto dto, @MappingTarget ItemDetail entity);
}