package com.example.SalesTransactionService.SalesTransaction.mappers;

import com.example.SalesTransactionService.SalesTransaction.dtos.RequestDto.WitnessInformationRequestDto;
import com.example.SalesTransactionService.SalesTransaction.dtos.ResponseDto.WitnessInformationResponseDto;
import com.example.SalesTransactionService.SalesTransaction.models.AgreementRegistration.WitnessInformation;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface WitnessInformationMapper {

    WitnessInformationMapper INSTANCE = Mappers.getMapper(WitnessInformationMapper.class);

    @Mapping(target = "id", ignore = true) // ID generated by DB
    @Mapping(target = "contractAgreement", ignore = true) // Relationship set in parent mapper/service
    WitnessInformation toEntity(WitnessInformationRequestDto dto);

    WitnessInformationResponseDto toResponseDto(WitnessInformation entity);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "contractAgreement", ignore = true)
    void updateEntityFromDto(WitnessInformationRequestDto dto, @MappingTarget WitnessInformation entity);
}